<?php

return [
    'langs' => ['en' => 'English', 'gu' => 'ગુજરાતી', 'hi' => 'हिंदी'],
    'bank_list' => [
        '1' => 'Allahabad Bank',
        '2' => 'Andhra Bank',
        '3' => 'Axis Bank',
        '4' => 'Bank of Bahrain and Kuwait',
        '5' => 'Bank of Baroda - Corporate Banking',
        '6' => 'Bank of Baroda - Retail Banking',
        '7' => 'Bank of India',
        '8' => 'Bank of Maharashtra',
        '9' => 'Canara Bank',
        '10' => 'Central Bank of India',
        '11' => 'City Union Bank',
        '12' => 'Corporation Bank',
        '13' => 'Dena Bank',
        '14' => 'Deutsche Bank',
        '15' => 'Development Credit Bank',
        '16' => 'Dhanlaxmi Bank',
        '17' => 'Federal Bank',
        '18' => 'HDFC Bank',
        '19' => 'ICICI Bank',
        '20' => 'IDBI Bank',
        '21' => 'Indian Bank',
        '22' => 'Indian Overseas Bank',
        '23' => 'IndusInd Bank',
        '24' => 'ING Vysya Bank',
        '25' => 'Jammu and Kashmir Bank',
        '26' => 'Karnataka Bank Ltd',
        '27' => 'Karur Vysya Bank',
        '28' => 'Kotak Bank',
        '29' => 'Laxmi Vilas Bank',
        '30' => 'Oriental Bank of Commerce',
        '31' => 'Punjab National Bank - Corporate Banking',
        '32' => 'Punjab National Bank - Retail Banking',
        '33' => 'Punjab & Sind Bank',
        '34' => 'Shamrao Vitthal Co-operative Bank',
        '35' => 'South Indian Bank',
        '36' => 'State Bank of Bikaner & Jaipur',
        '37' => 'State Bank of Hyderabad',
        '38' => 'State Bank of India',
        '39' => 'State Bank of Mysore',
        '40' => 'State Bank of Patiala',
        '41' => 'State Bank of Travancore',
        '42' => 'Syndicate Bank',
        '43' => 'Tamilnad Mercantile Bank Ltd.',
        '44' => 'UCO Bank',
        '45' => 'Union Bank of India',
        '46' => 'United Bank of India',
        '47' => 'Vijaya Bank',
        '48' => 'Yes Bank Ltd',
    ],
    'otp_valid_hours' => 2,
    /* Recharge Commission Percentage End */
    'pagination_page' => ['page' => 10],
    'bccmail' => 'savaliya11.ketan@gmail.com',
    'account_types' => [
        'Customer' => 'Customer',
        'Employee' => 'Employee',
        'Karigar' => 'Karigar',
        'Other' => 'Other'
    ],
    'process' => [
        'fieling' => 'FIELING',
        'setting' => 'SETTING',
        'first palish' => 'FIRST PALISH',
        'rohdium' => 'ROHDIUM',
        'casting' => 'CASTING',
        'repeat palish' => 'REPEAT PALISH',
        'fine melting' => 'FINE MELTING',
        'lc chaki-lathiya' => 'LC CHAKI-LATHIYA',
    ],
    'diamond_types' => [
        'A' => 'A',
        'B' => 'B',
        'C' => 'C',
        'D' => 'D',
        'G' => 'G',
        'L' => 'L',
        'P' => 'P',
        'T' => 'T',
    ],
    'diamond_size_types' => [
        'Big' => 'Big Stone',
        'Small' => 'Small Stone',
        'Bugget' => 'Bugget Stone',
    ],
    'price_cal_on' => [
        'PartyPrice' => 'Party Price',
        'ActualPrice' => 'Actual Price',
    ],
    'order_status' => [
        'Pending' => 'Pending',
        'Vaccum' => 'Vaccum',
        // 'Casting' => 'Casting',
        'In Production' => 'In Production',
        'Completed' => 'Completed',
        // 'Delivered' => 'Delivered',
        'Overdue' => 'Overdue',
        'Cancel' => 'Cancel',
        'Ignore' => 'Ignore',
    ],
    'order_status_manual' => [
        'Pending' => 'Pending',
        'Cancel' => 'Cancel',
        'Ignore' => 'Ignore',
    ],
    'order_status_inout' => [
        'Vaccum' => 'Vaccum',
        'Casting' => 'Casting',
        'In Production' => 'In Production',
        'Completed' => 'Completed',
        'Delivered' => 'Delivered',
    ],
    'order_status_outward' => [
        'In Production' => 'In Production',
        'Completed' => 'Completed',
        'Delivered' => 'Delivered',
        'Vaccum' => 'Vaccum',
    ],
    'order_status_stone' => [
        'Vaccum' => 'Vaccum',
        'Casting' => 'Casting',
        'In Production' => 'In Production',
        'Completed' => 'Completed',
    ],
    'order_status_stone_tag' => [
        'In Production' => 'In Production',
        'Completed' => 'Completed',
        'Delivered' => 'Delivered',
    ],
    'voucher' => [
        'goldbhav' => 'Goldbhav',
        'payment' => 'Payment',
        'loss' => 'Loss',
    ],
    'voucher_sub_types' => [
        'sale' => 'sale',
        'purchase' => 'purchase',
        'payment' => 'payment',
        'reciept' => 'reciept',
        'recovery' => 'recovery',
        'net loss' => 'net loss',
    ],
    'goldbhav_types' => [
        'sale' => 'sale',
        'purchase' => 'purchase',
    ],
    'payment_types' => [
        'payment' => 'payment',
        'reciept' => 'reciept',
    ],
    'loss_types' => [
        'recovery' => 'recovery',
        'net loss' => 'net loss',
    ],
    'confirm_by' => [
        'at_rv_office' => 'At Rv Main Office',
        'at_client_office' => 'At Client Office',
        'on_call' => 'Telephone',
        'on_mail' => 'Mail',
        'other' => 'Other',
    ],
    'reverse_type' => [
        'issue' => 'issue',
        'reciept' => 'reciept',
        'payment' => 'payment'
    ],
    'process_type' => [
        '' => '--select--',
        'None' => 'None',
        'Melting' => 'Melting',
        'Casting' => 'Casting',
        'Filling' => 'Filling',
        'Polish' => 'Polish',
        'Setting' => 'Setting',
        'Rhodiam' => 'Rhodiam',
        'Finalization' => 'Finalization',
        'General' => 'General',
    ],
];
